import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from '@vercel/analytics/next';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="grid items-center justify-items-center"><a href={`/`}>Math made fun</a></nav>
        {children}
        <Analytics />
        <footer className="grid items-center justify-items-center">
          Math made fun
          <div>View all link on <a href={`/sitemap`}>{`Sitemap`}</a></div>
          <a href="https://github.com/RisingSatalite/math-made-fun" aria-label="GitHub">🐱</a>
        </footer>
      </body>
    </html>
  );
}
